export const SAVE  = 'SAVE'
export const FIND_ALL_WIDGETS  = 'FIND_ALL_WIDGETS'
export const DELETE_WIDGET  = 'DELETE_WIDGET'
export const ADD_WIDGET  = 'ADD_WIDGET'
export const HEADING_SIZE_CHANGED = 'HEADING_SIZE_CHANGED'
export const  SELECT_WIDGET_TYPE = 'SELECT_WIDGET_TYPE'
export const HEADING_TEXT_CHANGED = 'HEADING_TEXT_CHANGED'
export const PREVIEW = 'PREVIEW'
export const IMAGE_URL_CHANGED = 'IMAGE_URL_CHANGED'
export const WIDGET_NAME_CHANGED = 'WIDGET_NAME_CHANGED'



